### ISSUE TITLE
Perseus causes Safe Mode if WatchMirrorMute is installed

### ISSUE THREAD

**Issue by JiDoan** [udevsharold/perseus#3]
Perseus will cause the Springboard to enter Safe Mode if WatchMirrorMute is installed and `Mirror mute on iPhone lock/unlock` is enabled. Attached is the crash log of the issue. When turning off the feature on WatchMirrorMute or downgrading Perseus to 1.0.1, the issue goes away.

[Crash Log](https://github.com/udevsharold/perseus/files/6051689/text-7F499235C1EE-1.txt)

**Comment by udevsharold** [comment]
It was fixed in latest WatchMuteMirror update today.
