### ISSUE TITLE
Perseus conflicts with WatchMuteMirror

### ISSUE THREAD

**Issue by u0xpsec** [udevsharold/perseus#4]
Device: iPhone 11 Pro
Software: iOS: 14.3, unc0ver: 6.1.0, Perseus: 1.1.5, WatchMuteMirror: 1.1.2

Steps to reproduce: install Perseus and install WatchMuteMirror or switch order of installation. 

Results: on respring after installation, springboard will crash and send device straight to safe mode.

Logs linked here: 
[Log 1](https://pastebin.com/raw/vVbEkD9S) 
[Log 2](https://pastebin.com/raw/W3H8mBuu)

**Comment by udevsharold** [comment]
It was fixed in latest WatchMuteMirror update.
